### ISSUE TITLE
Configurable Cards

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#103]
Discuss whether users should be able to configure a custom set of cards.

Code is prepared and does support that. Currently the client contains hard-coded card configuration:

```
[
    {label: '?', value: -2, color: '#bdbfbf'},
    {label: '1/2', value: 0.5, color: '#667a66'},
    {label: '1', value: 1, color: '#839e7a'},
    {label: '2', value: 2, color: '#8cb876'},
    {label: '3', value: 3, color: '#96ba5b'},
    {label: '5', value: 5, color: '#b6c76b'},
    {label: '8', value: 8, color: '#c9c857'}
]
```
The rest of the app is agnostic to the content of that config, as long as every card specifies a label, a value and a color.

## Idea

* Remove hardcoded "cardConfig" from client. Default "cardConfig" is set in the backend as property on the "room" object. Client receives that together with rest of room state on "joinedRoom" event.   (and can be put onto redux store)
* Introduce "setCardConfig" command and "cardConfigSet" event.
* Provide UI for users to set custom cardConfig

**Comment by xeronimus** [comment]
![userMenu_customcardconfig_ui](https://user-images.githubusercontent.com/1777143/94362700-87143700-00bd-11eb-863c-d303ed66eb72.png)
![room_customCards](https://user-images.githubusercontent.com/1777143/94362705-8a0f2780-00bd-11eb-8dc9-f88102f1eed8.png)

Working implementation including UI.   Still pondering about added complexity (voluntary..) versus added flexibility for (power) users...

**Comment by ackvf** [comment]
This is awesome! How do I try this? I can't seem to find Custom Cards block anywhere.

**Comment by xeronimus** [comment]
Hi,

thanks very much. my thoughts exactly:

**Summary**:  If you want to use "Custom Cards", use a fresh room. 
If you want to use multiple set of custom cards on a regular basis, create separate rooms.

I did not merge this new feature into the master branch. Thus it is not yet deployed.  you could test it out, if you build and run the branch https://github.com/Zuehlke/poinz/tree/103-configurable-cards locally.

Just from looking at the screenshot, do you think, the json textarea works for you?

**Comment by ackvf** [comment]
Yeah, it's perfect. The interface seems simple enough as well. Anyway, I suspect that people will be writing the JSON in an IDE anyway.

**Comment by xeronimus** [comment]
Deployed in release 0.7.0
