### ISSUE TITLE
how do I reuse my old character?

### ISSUE THREAD

**Issue by ackvf** [Zuehlke/poinz#119]
I remember reusing my old nickname with avatar seamlessly, but right now I don't know how to achieve that.
![image](https://user-images.githubusercontent.com/2313018/94008379-380b9080-fda3-11ea-8f43-7dcf001430eb.png)

Was it the nickname? or the email?
Why I can't use my old nickname `Qwerty (Vítězslav)`? I can't use spaces and brackets now.

**Comment by xeronimus** [comment]
Hey there,

thank you for bringing that up. 
I did introduce a username validation pattern with #99 .  Maybe the special char limitation was a bit prematurely.

Which special chars, would you say, should be allowed in the username?

**Comment by xeronimus** [comment]
I changed the validation pattern of the username to allow special chars again. Length limitation still applies (currently 80 chars).


To answer the question in the issue title:   your browser reuses the "character" automatically, as long as you do not clear localStorage (i.e. and use the same browser...)
