### ISSUE TITLE
Remove Story / Change Story

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#12]
I just started adding some stories to prepare an estimation meeting and then I noticed that I would like to correct the first Story I added.

Some possible solutions:

* Allow the user to remove stories
* Allow the user to change stories

Workaround at the moment:

* Create a new room and start over with adding stories

**Comment by xeronimus** [comment]
I implemented editing for stories.  you can check it out at the test deplyoment ;-)

**Comment by adiherzog** [comment]
Editing works as expected. Removing a story is not that important to me. So this issue can be closed from my perspective.

**Comment by xeronimus** [comment]
I Agree. With deletion, there are further questions like:
- Would we need an undo function ("Story was deleted. Undo...") . Or more traditionally: confirmation "do you really want to delete story"
- Or is the "loss" of a story that was accidentally deleted acceptable..?
