### ISSUE TITLE
Possibility to use custom set of card values

### ISSUE THREAD

**Issue by ackvf** [Zuehlke/poinz#124]
My team loves the simplicity of your app and we started using it for almost any voting while on calls. It would be great if we could simply swap the card set for say `A, B, C, D, E` or `1, 2, 3, 4, 5`. Right now we first need to agree on which card represents what value, but the simplicity of your app still overcomes any such overhead. What do you think?

**Comment by xeronimus** [comment]
Hi there, thanks very much for the input.
Actually there is already an issue regarding this:  see #103  .

Could you check out the sceenshots and give me some feedback?
