### ISSUE TITLE
Make room name guessing harder

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#13]
I just created my first room with a short and memorable name. This is of course very good and I don't have to send a link because I can just tell people the room name. On the other hand somebody could just try out some likely room names and see what we are doing in my top secret project ;-) Long story short: Some users would prefer if rooms could be secured somehow.

Ideas:
- Passphrase required to join the room (can be enabled optionally by the room creator)
- Room URL contains a long random string which is hard to guess (also optional or maybe even default and "easy URL" only on demand).

**Comment by xeronimus** [comment]
* New default behavior: Creating a room will generate a random uuid as roomId.
* Rooms will no longer be created "on-the-fly", when trying to join inexistent room.
* One can (optionally) define room-alias when creating room. This allows joining room with https://host/[roomAlias]
