### ISSUE TITLE
Improve workflow to set the user name

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#14]
As a guessing team I would like to know everybody'y name so that I know who guessed what.

Currently setting the name is a bit hidden in the menu. I propose changing the workflow so that each user that joins the room has to set their own user name before they can participate in the session.

**Comment by xeronimus** [comment]
I gave that some thought and I am still not sure.

In my opinion, it is important to keep the tool as simple as possible. If we require a username, we add another "barrier".

Also, the username is stored in local storage. so (with the same browser) you only have to enter it once.

What about a "info box"  next to the settings cog if the username is missing?

**Comment by adiherzog** [comment]
In my opinion using the tool without setting the username does not make sense because the other users of the session always want to see who voted what.

Therefore I think it's easier for the user if he get's prompted to set the username first instead of letting him figure out how to go to the menu and set it there.

Then for every subsequent use of the tool the username prompt is not necessary anymore as the username is stored already.

An info box would be ok as well, but not as good from a usability perspective.

**Comment by xeronimus** [comment]
merged and deployed. version 0.1.1.
you can test it by removing poinz_presetUserName from localstorage (chrome dev tools), refresh the app, then join a room
