### ISSUE TITLE
Rename "Visitor" option or add explanation

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#15]
As a user I want to understand the impact of selecting any options in the menu without trying it out first so that I can decide more efficiently which options I want to select.

Currently the option "Visitor" is not as clear as it could be (until one actually tries it out, then it becomes clear). Therefore I would propose one of these improvements:

* Tooltip that explains the feature (not suitable for mobile though)
* Short explanation in brackets
* Rename the option to something like "I am only here to watch"

**Comment by xeronimus** [comment]
I added a hint that describes the "visitor" flag.  

could you review the changes on the test deployment, and give me some feedback?

**Comment by adiherzog** [comment]
Looks good to me. I like that the change is now done immediately without clicking "Save".

**Comment by xeronimus** [comment]
That's right.  In a very early version there was no "save" button at all. I added it because users with mobile devices couldn't save their username (with "enter" key).

Now the "save" button is for the username only, the visitor checkbox toggles the visitor flag immediately.
