### ISSUE TITLE
Optionally protect room with simple password

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#156]
As a room creator, I want to be able to set a password in order to protect my room against unwanted joiners.

In order to invite others, I will need to share the roomId (i.e. the url) AND the password

On joining a room, the user will be prompted for the password.

**Comment by xeronimus** [comment]
It was not all straightforward, there are some edge cases to consider.  However, I think I got a MVP ready:

* Users can set an optional password together with a custom roomId or a auto-generated roomId

![image](https://user-images.githubusercontent.com/1777143/105578774-d70cbd00-5d82-11eb-9d25-ee48b6d5d4bf.png)

* Users get promted for the password, if they want to join a protected room

![image](https://user-images.githubusercontent.com/1777143/105578794-04f20180-5d83-11eb-860a-1fe0317536f3.png)

* Users can clear or re-set the password in the room settings panel

![image](https://user-images.githubusercontent.com/1777143/105578814-2357fd00-5d83-11eb-853a-d83c359701cd.png)

indication if no pw is set:

![image](https://user-images.githubusercontent.com/1777143/105578826-379bfa00-5d83-11eb-9a34-6fea1abcd9d3.png)


@chschoenenberger would you think that works for you?


Some unfixed issues :  if you loose the connection to the backend (e.g. you are on a mobile phone), the client will "re-join" as soon as the connection is re-established.  up until now, you would not notice this.  
now, if you are in a protected room, you will be promted with the password field, on connection re-establish...

**Comment by chschoenenberger** [comment]
Looks great. Will test this in our next sprint planning and will let you know if we encounter unexpected behavior! Thanks a lot for the quick resolution 😊

**Comment by xeronimus** [comment]
deployed 0.9.0
