### ISSUE TITLE
Sorting of stories

### ISSUE THREAD

**Issue by chschoenenberger** [Zuehlke/poinz#157]
Possibility to sort stories by name, date added, ... would be nice. This would probably be connected to #18

**Comment by xeronimus** [comment]
Thanks for the suggestion. that'll be easy to implement.  

@chschoenenberger  where would you place the additional UI elements for sorting (and think about ASC / DESC as well ;) )

**Comment by chschoenenberger** [comment]
@xeronimus I guess between the "Add Story +" button and the top story would make sense the most.

**Comment by xeronimus** [comment]
I implemented a draft:

![image](https://user-images.githubusercontent.com/1777143/105756339-c314b700-5f4c-11eb-8ece-c48858abfe48.png)

And I threw in a filter field as well:

![image](https://user-images.githubusercontent.com/1777143/105756459-f2c3bf00-5f4c-11eb-8366-69fc500972ed.png)

@chschoenenberger   any feedback?

**Comment by chschoenenberger** [comment]
Looks great! 😊 Happy to try it out for our next planning and provide more feedback.

**Comment by xeronimus** [comment]
deployed. 0.9.1
