### ISSUE TITLE
Remember last n rooms on join screen

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#16]
When joining a room from http://52.37.30.226/ it would be nice to see the rooms that I recently used as proposals. This would especially be helpful if the room names are not so easy to remember and I lost / forgot the link.

I see this as low to medium priority, but it would be nice.

**Comment by xeronimus** [comment]
Could you elaborate on the use case.

Do you re-use your rooms? I expected teams to create a new room for each meeting, e.g. "SuperProject-Sprint22"

Or do people close their browser during meetings?

**Comment by xeronimus** [comment]
I implemented a simple room history on the landing page. you can check it out at the test deployment http://52.37.30.226/

**Comment by adiherzog** [comment]
In my project we use the same room for all sessions. Therefore the history is useful if somebody remembers the domain name (assuming there will be one that is easy to remember) but not the room name. I think the way you implemented it is fine, thanks :-)
