### ISSUE TITLE
Summary Pane

### ISSUE THREAD

**Issue by gotdibbs** [Zuehlke/poinz#163]
Hey there, thanks for building this app!

Curious as to your thoughts on adding a summary pane of sorts for the end of a round. Could be something that displays:

- Average points
- Point range

I find it helpful to know at a glance with larger teams.

**Comment by xeronimus** [comment]
Hi,  

thank you very much for the suggestion!  I like it!

Here is my proposal:
- as soon as the story is revealed (either automatically or manually), we display a summary.
- the summary will be placed in the area where the cards are displayed during estimation. i.e. below the "New Round" button.
- the summary displays 
    - number of users that estimated  (e.g.  " 7 of 8 users did estimate")
    - highest estimated value
    - lowest estimated value
    - average


@gotdibbs  How should we handle "special"  cards like "?"   "Break"    "BIG"  . Technically they have a numerical value... By default they have negative values....

**Comment by xeronimus** [comment]
![image](https://user-images.githubusercontent.com/1777143/106940734-31fac880-6722-11eb-8a84-9acaccacdb91.png)
![image](https://user-images.githubusercontent.com/1777143/106940795-45a62f00-6722-11eb-8b5c-30a095aa9205.png)
![image](https://user-images.githubusercontent.com/1777143/106940858-5a82c280-6722-11eb-9268-af0a420c6ce0.png)

**Comment by gotdibbs** [comment]
Hey! I think what you just shared looks like a good start to me! Some alternative thoughts on UI:

1. You could just list out all the cards, and show them with percentages of the vote. Possibly putting the percentages below each card, flag the ones that are high low there as well, and/or "filling" the card with a highlight that covers the matching percentage of the vote. Conceptually this route sounds the best to me, but 🤷 
2. Keep iterating on what you have, but instead of a true average, display the card nearest the average by calculating the average then finding the card with a difference from the average that is closest to zero, hacked example below:

```javascript
const pointValues = [-10, 1, 3, 5, 8, 20, 100];
const teamPoints = [-10, -10, -10, 3, 5];

const average = points.reduce((sum, value) => sum + value) / points.length;

console.log(average);

return availablePoints.reduce(function (prev, curr) {
    return (Math.abs(curr - average) < Math.abs(prev - average) ? curr : prev);
});
```

**Comment by xeronimus** [comment]
Thanks for your inputs, I'll prototype an alternative way of presenting the summary :)

btw, just out of curiosity:  what's a typical number of participants in your estimation sessions?

**Comment by gotdibbs** [comment]
You bet! Happy to help, thanks for your quick responses.

Our team is 11 right now, which is larger than we'd like, but we're about to split into two in a month or so.

**Comment by xeronimus** [comment]
I like this one:

![2021-02-06 07_29_27-Window](https://user-images.githubusercontent.com/1777143/107111081-67500500-684d-11eb-94e3-ed6683b75d73.png)
![2021-02-06 07_30_27-Clipboard](https://user-images.githubusercontent.com/1777143/107111085-67e89b80-684d-11eb-907c-cf75729604aa.png)
![2021-02-06 07_30_50-Window](https://user-images.githubusercontent.com/1777143/107111086-67e89b80-684d-11eb-8299-6c27db1c9263.png)

still not sure about displaying an "average"... Isn't it obvious enough with the new way of showing the summary...?

**Comment by gotdibbs** [comment]
Oh cool idea! Yeah I think the way you've set it up gets at the underlying thought behind showing an average.

I love how that turned out!

My only possible feedback from here would be that it might be cool to see how it looks with the number of votes as an overlay taking the entire top or bottom of a card so that you could actually show "X votes" as opposed to just a number. That said, I like it as is too!

**Comment by xeronimus** [comment]
![image](https://user-images.githubusercontent.com/1777143/107123240-bffabe80-689c-11eb-819c-8eed4d5aa791.png)

as soon as you introduce text, you need space and you need a translation .. hm..  not yet sure..  
what about adding an icon after the count?

**Comment by gotdibbs** [comment]
Hmmm ah yes it does look like it could get squished fast. I think given those constraints, my opinion would be that your original badge solution is prolly best here.

**Comment by xeronimus** [comment]
deployed 0.10.0

**Comment by gotdibbs** [comment]
This one and the other one look awesome, thanks so much!!

Def let me know if there's anything else I can provide feedback on or anything.

**Comment by keremcankabadayi** [comment]
Hi all, we are using average all the time. I think it should be showed after reveal in the story section with 1 decimal point. It can also be added in settings on / off.

What you think?

![image](https://user-images.githubusercontent.com/23381187/110796785-674a8700-8289-11eb-8c82-84d8fe956ad7.png)

**Comment by xeronimus** [comment]
HI @keremcankabadayi  

thanks for your suggestion.  could you share some insights into how you use averages? Or in other words, why would you like to display the average?

In my understanding,  the goal of an estimation round is to agree on one distinct value, right?
so if the results of a round vary, you need to further discuss and agree on one value or you start an additional round. 

what "benefit" brings the average?

**Comment by gotdibbs** [comment]
For what it's worth, that has been our experience @xeronimus. The average idea is nice in theory, but in practice we still have to agree on one whole distinct value. I am therefore also curious if there might be some value to this request I haven't thought through either.

**Comment by keremcankabadayi** [comment]
hi again, we vote stories/taks estimation hours for those works. for example, project-001 is voted average 5.4. We set story point for this task 4 or 6 approx. (hours). And we design sprints based on these points sum (for using p/d).

**Comment by xeronimus** [comment]
what if.....   
 ...on the "Summary Pane", you could "settle" on one of the estimated values?

## Scenario:
- multiple users in the room estimate Story "project-001"
- three users estimated a value of "3"
- two users estimated a value of "5"
- PoinZ reveals the story and displays the summary pane with the cards "3" and "5" highlighted.

NEW:   by clicking on either "3" or "5", you could "settle" on a value. The story will then store the clicked value as "consensus".

**Comment by xeronimus** [comment]
I implemented the "what if" scenario mentioned above.  Feels good, works fine.

Two users estimated, story is revealed. They do not yet agree...
![Screenshot from 2021-03-13 08-45-53](https://user-images.githubusercontent.com/1777143/111023343-cff44980-83d8-11eb-936e-eaee65f172d2.png)

Team discusses and comes to an agreement. Someone (Scrum Master / Moderator) clicks on one of the two highlighted cards ("5" and "8") to **"settle"** the estimation round. (in this case clicks on "5").

![Screenshot from 2021-03-13 08-46-04](https://user-images.githubusercontent.com/1777143/111023366-fc0fca80-83d8-11eb-9b6d-2f78b20f25e5.png)

Now the story has "5" stored as consensus.

... now we have to decide whether to deploy this new feature...

**Comment by keremcankabadayi** [comment]
Hi again, great impl. I didnt thought like you did. restriction numbers only team picked great idea. loved it.
Even though, we may need average to see.
Real life scenario:

1. project-001 voting about 30 team members. (1, 2 x 5, 5 x 8, 13 x 10, 21 x 6)
2. average 10.2. we would discuss this task can take 8 or 13. and probably we would pick 13.

**Comment by xeronimus** [comment]
Of course we can [technically] display an average value:

![image](https://user-images.githubusercontent.com/1777143/111060904-96871100-84a0-11eb-8fc9-629df7d9e1b1.png)
(I do round to one digit after the decimal point)


My thoughts on that (and I hope, I'm not stepping on anyone's toes here..):

- In my experience, if the team has a quite big "spread" (from 1 to10) this means, colleagues have a completely different understanding of "what the story is about". Then it would be a good thing to discuss and start another estimation round. (instead of just settling on the "nearest to average" value... 
- Cards can have negative numbers (e.g. the default card "?" has a value of -2)

**Comment by keremcankabadayi** [comment]
my examples are unreal. we dont have much 1point, 13point disagrement on tasks. If we have, we discuss about why we vote that point.
we dont use negative values. always use Fibonacci numbers.

**Comment by xeronimus** [comment]
what do you think about my proposal, displaying the "numerical average" on the summary pane?

**Comment by keremcankabadayi** [comment]
> 
> 
> what do you think about my proposal, displaying the "numerical average" on the summary pane?

No problema. Enough to see after reveal somewhere. I'm waiting deploy to see differences.

**Comment by xeronimus** [comment]
deployed 0.11.0
