### ISSUE TITLE
Estimating without Stories / Backlog

### ISSUE THREAD

**Issue by gotdibbs** [Zuehlke/poinz#164]
I noticed that you must first create a story to run a session, but that you can then run new rounds on the same story over and over.

I think it would be great, for those of us that use our own story tracking system, to be able to just run a pointing session independent of having to enter a story in your tool and thus duplicating a backlog that exists elsewhere.

Thanks for your consideration!

**Comment by xeronimus** [comment]
Hi,  

other teams gave me this feedback also. They "solve" it by creating a placeholder story with a quite generic title (e.g. the Project name).
They then reuse the room, so they don't need to re-create the story for every estimation meeting. (A PoinZ room will be kept for 30 days if unused). On the other hand, you only need to enter a title and hit the Enter button...

if this does not suit your needs, I would have to think about how to implement this.  Would this be a settings flag for a room, during creation? something like "no-story-mode" ?

**Comment by gotdibbs** [comment]
Yeah, and that approach has worked fine for us! It is just a bit weird when you're first starting out, so not an ideal onboarding flow for new folks.

My thought would be if to setup the logic such a placeholder story is used if one hasn't been created. In that way, you could always start with estimating off the board, but once you've created a story, it just goes back to the default logic.

I'd be happy to spike on this, just haven't had a chance to dig into your codebase yet, so just let me know if you'd like me to take a peek myself!

**Comment by xeronimus** [comment]
hm. big code change.  everything is based on the idea of "estimating a story". Not considered the idea of "no story present".

I see the argument with the experience for new users...

**What would be easy:** when a room is created, just create a sample story along with it. The description could contain a most simple "quick start" text. If you want, you could ignore it and just estimate this "instructional" story.

Just one challenge:  translations are currently done client-side only.  if the backend would create the sample story, we would need to translate the title and description on the backend...

**Comment by xeronimus** [comment]
Automatically added story on room creation:

![image](https://user-images.githubusercontent.com/1777143/107118599-376f2480-6882-11eb-92d4-6a37514f069b.png)

**Comment by gotdibbs** [comment]
Dang you beat me to it haha, that's what I was thinking of looking into as well -- a default story.

I love how your approach adds a sort of intro/help as well! 10/10 would ship right now!

**Comment by xeronimus** [comment]
deployed 0.10.0
