### ISSUE TITLE
Statistics after each round

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#17]
As moderator of the estimation session I'd like to have a very quick overview of the estimation result.

Ideas how this could be realized:

* Table with statistics, e.g. 
  * 3 times 1 SP
  * 2 times 2 SP
  * 1 times 5 SP
* Reshuffle the people so that everybody who has the same estimation is in a cluster and the clusters are sorted from small (left) to big (right). This would be my preferred solution.

When a new round is started, the statistics / reshuffling should be removed so that every round is started on neutral ground.

This is one of the most important features that are missing at the moment as it directly impacts estimation performance.

**Comment by adiherzog** [comment]
This is actually not as important as I thought. With about 7 people in the room it's still quite easy to get an overview of the estimates.

**Comment by xeronimus** [comment]
I also thought about this. this would be the first feature that is not available in "real" life ;-)

(as far as I know, colleagues do not change seats and "sort" themselves after estimation...)
