### ISSUE TITLE
Password Protected Rooms: Flow Improvements

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#173]
Since #156 users can protect a room by setting a password. Either during creation (on Landing page) or for existing rooms in the room settings panel.

**There are some shortcomings with the current solution:**

1. Major: We don't ask to enter the password twice when setting it -> when the user mistypes, he will not notice it and cannot join his room afterwards
2. Major: We don't have any means to "recover" a room, in case of "forgotten" password
3. Minor: User does not get notified (nicely) when "setPassord" fails due to validation (e.g. max password length is currently 50 chars). Action log shows error "Command "setPassword" was not successful.  Command validation Error during "setPassword": String is too long (190 chars), maximum 50 in /payload/password"
4. Minor: When setting a password for an existing room, no "tokenIssued" event is created (neither for the user that sets it, nor for potential other users already in the room). This leads to a "not authorized" error, when trying to export stories from the room...

**Comment by chschoenenberger** [comment]
Hi @xeronimus 
My feedback to the shortcomings:

1. Was not really an issue for me, as I used a password that I generated with my password manager and shared it with the team directly. A possibility could be to generate passwords for the user which can be shared with the team. 
2. I guess recovery is not really possible as users don't register for the solution. There's know way you can verify the users identity... Therefore, I suggest to just notify the user that they should store the password securely as the room is lost without it.
3. I guess a pop-up would be nice here
4. Should it be allowed to create a PW for an existing room? That might be a bit weird as I could "guess" peoples rooms and "lock" them with a password

**Comment by xeronimus** [comment]
thanks for the feedback, much appreciated!

2. We could create a "recovery" token, display it once to the creator of the room. With the token you could later reset the password.
4. This is possible now and has been since the introduction of PW protected room. If we prohibit that, you would have to decide during creation of the room... or in other words, once the room is created, you cannot later down the road decide on setting a password protection...  Also I think the re-set / change of the password should anyways still be allowed... (also possible right now)

**Comment by chschoenenberger** [comment]
2. Yeah that would probably be the same issue... Don't think that really helps.
3. (I guess you meant 4?) True, you should keep that this way then.
