### ISSUE TITLE
Support docker image versions

### ISSUE THREAD

**Issue by ociotec** [Zuehlke/poinz#187]
Hi, first of all thanks for your work! we do really enjoy using your tool for planning poker sessions :)

Is there any plan to create docker image versions as it's done in other images? I mean, typically each time a project makes a new release with docker image support a new image version is also released...

This is very useful to point to an specific version of the docker image, instead of pointing to "latest".

Thanks in advance.

**Comment by xeronimus** [comment]
Hey there, thanks for the suggestion, should not be a problem..

Currently i'm on vacation. I can look into it next week.

**Comment by ociotec** [comment]
Thanks!!!!

**Comment by xeronimus** [comment]
Hey @ociotec ,

I'm not the docker expert, so I'm glad for any input.

our build script (travis) builds a docker image and pushes it to the docker registry:  https://hub.docker.com/r/xeronimus/poinz

always tagged with "latest".

If I understand correctly, this is done in the script https://github.com/Zuehlke/poinz/blob/master/build/dockerImage.js, line 99

```javascript

 const cmdArgs = `build -t ${userAndProject}:latest -t ${HEROKU_DEPLOYMENT_TAG} .`;

```

so, in order to publish a correctly tagged image, we would need to change that to:
"if on master branch, tag the image with the current version from package.json"

```javascript

if(gitInfo.branch === 'master'){
 const cmdArgs = `build -t ${userAndProject}:latest -t ${HEROKU_DEPLOYMENT_TAG} -t ${pkg.version}.`;
}

```

?

**Comment by ociotec** [comment]
Hi, almost on track… you need to put the registry +image path before the image version:

```python
if(gitInfo.branch === 'master'){
 const cmdArgs = `build -t ${userAndProject}:latest -t ${HEROKU_DEPLOYMENT_TAG} -t ${userAndProject}:${pkg.version} .`;
}
```

This should be done only when there is a tag on master I guess… not sure how to do it on your CI setup…

**Comment by ociotec** [comment]
Then of course you also need to push both images (latest & the tag one), this should be done in two different docker push commands (annoyingly there is no way to combine several pushes into one command as it’s possible with docker build).

**Comment by xeronimus** [comment]
could you propose the change to the travis.yml  file? 

assuming, the build script tags the (same?) image with  "latest"  "xeronimus/poinz"  and "0.11.3"

**Comment by ociotec** [comment]
I’m not sure about Travis syntax… according to info at https://docs.travis-ci.com/user/deployment#conditional-releases-with-on maybe it’s something like this:

```yml
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
      if [ "$TRAVIS_TAG" == "" ]; then
        VERSION="latest"
      else
        VERSION="$TRAVIS_TAG"
      fi
      docker push xeronimus/poinz:latest;
    fi
```

**Comment by stawik-mesa** [comment]
Hey there, also thank you for this great project. I just opened a PR with a basic implementation of using git tags as image reference. Feedback is always welcome ;)

**Comment by xeronimus** [comment]
thanks @stawik-mesa for the contribution.

you now fetch the version from git tags, no longer from package.json.  
So my conclusion, the docker image will be tagged with the version, only if the current commit is tagged in git.

**Comment by stawik-mesa** [comment]
@xeronimus 
Yes that's correct. I can also change it to just tag it with the version from package.json if branch is master.

**Comment by stawik-mesa** [comment]
But GitHub tags are unique, while a change of the code without a change on the version in the package.json will overwrite the existing tagged image.

**Comment by xeronimus** [comment]
makes total sense.  thanks for clarification.
I would suggest we leave it at that for the moment, and see how it works out.

**Comment by xeronimus** [comment]
works as expected.  image was tagged (0.11.4) and pushed automatically, see https://hub.docker.com/r/xeronimus/poinz/tags?page=1&ordering=last_updated
