### ISSUE TITLE
Estimate without adding stories

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#19]
In my team we don't need to add stories to the estimation board. It's enough to have the relevant story open in the backlog management tool. Currently one has to add at least one story and select it to start estimation.

For ease of use I propose to make estimating possible even when no story is added to the board. This could e.g. be done by adding a default "dummy story" to each room which is selected by default.

**Comment by xeronimus** [comment]
Assuming every participant is aware of the current story that is estimated?  (e.g. because you announce it in chat/voice chat)

**Comment by adiherzog** [comment]
Exactly. In a typical estimation round the story is anyway discussed quite a bit before estimation happens. I think the story feature is still good for certain use cases (e.g. for preparing the estimation session in advance), but it should not hinder users who don't want to use it.

**Comment by xeronimus** [comment]
I agree. But I would say that the current workaround (quickly add a "placeholder" story and use the "New Round" button for estimating new story) is feasible for now... ?

**Comment by adiherzog** [comment]
The workaround is ok but maybe keep this idea in mind for later.
