### ISSUE TITLE
Ignore miscellaneous cards

### ISSUE THREAD

**Issue by xpomul** [Zuehlke/poinz#192]
This is related to issue #163.

The numerical summary displayed takes into account the cards with negative values (e.g. „?“ and „BIG“).
This is not really usable, because usually „?“ would be chosen by people that don’t have enough confidence to submit a vote.

I’d propose one of these:
* generally ignore negative estimation values for the purpose of min/max/numerical average, or
* introduce a room setting to ignore negative estimation values, or
* introduce a special non-numerical value which we can assign to cards that should not be counted.

**Exoected outcome:**

if a vote is 2x8, 3x13, 2x?, the result should be 2*8 + 3*13 = 55 - divided by 5 valid votes (not counting the 2 voters for „?“): = 11

**Background:**

To use the auto-reveal, everyone needs to vote; but if not everyone feels confident to vote (we are a rather big team), then they only can decide not to vote or to make the numerical average unusable...

**Comment by xeronimus** [comment]
Hi @xpomul,

Thank you very much for your feedback. I can relate to that...
So I think we would then go with your first solution - ignoring all negative values...

 @gotdibbs any thoughts on this one?

**Comment by xeronimus** [comment]
deployed in 0.4.11
