### ISSUE TITLE
Change estimation after cards are uncovered

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#20]
I'm used to being able to change my estimate even after the cards are uncovered. This is possible in another tool we use for estimations.

Whether this is actually a feature or problematic should be discussed.

**Comment by xeronimus** [comment]
why should this be allowed? if the participants discuss their (first) estimation round, and colleagues change their mind. I think a new round should be started?

or the group agrees right away (by discussing). and the "moderator" can write down the final estimation.
(or in the future, save the final value, see #2)

**Comment by adiherzog** [comment]
It would allow for a more dynamic re-estimation on the fly. So if somebody changes their mind because of an argument they hear in the discussion they can immediately change their estimation. This would make a second round unnecessary in certain cases.

But I also see that certain people would explicitly NOT want this feature and would see it as a bug.

**Comment by xeronimus** [comment]
implemented in a feature branch. currently not merging into master.
