### ISSUE TITLE
Quick action for Spectator/Excluded

### ISSUE THREAD

**Issue by ackvf** [Zuehlke/poinz#200]
Nobody ever comes into settings and finds the option to **exclude** themselves. I propose two changes

- Add the **Exclude button** to the character menu
- Make this button available globally, like the **Kick User** action

![image](https://user-images.githubusercontent.com/2313018/130793245-b2251d52-9db0-41bf-b181-fe4d160f1c7f.png)

**Comment by xeronimus** [comment]
Thanks so much for the suggestion!

to clarify: 

- would you only display the "exclude" icon for your own user   (just a change in the UI, does not change current rules/implementation in the backend)
- would you allow mark other users as "exclude" (a change in current rules )

**Comment by xeronimus** [comment]
implemented in 0.11.5
