### ISSUE TITLE
Persuade <input> name to suggest the user's name

### ISSUE THREAD

**Issue by ecaron** [Zuehlke/poinz#205]
Multiple users have reported that the input field, in Chrome, is suggesting prefilling the user's browser-stored credit card information.

Would you consider setting [autocomplete="name"](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) on the name field to both prevent credit card & encourage better autocompletions?

**Comment by xeronimus** [comment]
0.11.6
