### ISSUE TITLE
Placement of "Reveal" and "New Round" cause accidents

### ISSUE THREAD

**Issue by ecaron** [Zuehlke/poinz#206]
Accidentally double-clicking the "Reveal" space can cause the "New Round" to be triggered, based on the placement of "New Round" & lack of confirmation.
![new-round](https://user-images.githubusercontent.com/70704/131888260-39dce70a-beb6-442f-9777-7dda8e95f19b.png)
![reveal](https://user-images.githubusercontent.com/70704/131888263-4634726d-422e-495f-9969-331c238cc387.png)

Suggested solved:
* Right-align the "New Round" button, by "Next Story"
* Have a "Are you sure?" popup on "New Round" (with a "Don't show again" option)
* Introduce a time delay between "Reveal" being clicked and "New Round" appearing

**Comment by xeronimus** [comment]
0.11.6
