### ISSUE TITLE
Flash symbol shown for many participants even if they are actually connected

### ISSUE THREAD

**Issue by adiherzog** [Zuehlke/poinz#21]
Is this a bug or a feature? I would assume that the flash indicates connection loss.
![image](https://cloud.githubusercontent.com/assets/1777143/13673601/10f856b6-e6da-11e5-93dd-76ef3e8a3cba.png)

**Comment by xeronimus** [comment]
It does. can you specify the bug? 
which browsers used? mobile devices or desktop?

**Comment by adiherzog** [comment]
I need to get some more information on this first.

**Comment by xeronimus** [comment]
Could you also verify that some of your colleagues used an iPhone (see #10)
