### ISSUE TITLE
Estimation Matrix

### ISSUE THREAD

**Issue by martin-sos** [Zuehlke/poinz#234]
As a Scrum Master I would like to empower and support relative estimation of stories. For this, our team uses an "Estimation Matrix" like here 
![image](https://user-images.githubusercontent.com/98313614/150758202-2edd7e26-bd3e-4839-a0d2-d55d714d03be.png)

1. It would be super cool if PoinZ would generate such an estimation matrix on the fly during a running estimation session. This way the team would see their last estimates in an agregated way and could use this representation to relatively estimate the next story. 

2. It would be even cooler if one could setup an estimation matrix in the tool by hand. Once a session is running, newly estimated items would be then added to the existing matrix to support the current session. Once another session is started, the newly added items would disappear again.

**Comment by xeronimus** [comment]
Something like this?

![2022-01-29 08_10_55-Window](https://user-images.githubusercontent.com/1777143/151651555-3dd5f3ad-5a55-4cef-ae71-b360072fbfe1.png)

this is an implementation of your suggestion 1. 

2. is not yet clear, and we always have to think about making poinZ not too complex..

**Comment by martin-sos** [comment]
Hey, yeah this matrix reflects the main idea. cool :-)! Before extending with new stuff, I would rather use it with the team and provide feedback on that. 
I would have already ideas like "can we extend the top row of the table by user defined pictures for each fibonacci number? as it is represented in the screenshot..." but yeah...I think some more feedback would be needed for this. 

And I also think the "2." could be a bit over the top, just my vision.

**Comment by mariokaufmann** [comment]
Hi! I allowed myself to quickly throw together another possible layout for such an estimation matrix (by shamelessly editing your screenshot):

![poinz_matrix](https://user-images.githubusercontent.com/8816947/151663887-6cadf267-d3f2-4831-b439-49e755d1a0cf.png)

The advantage of such an approach in my opinion would be that more stories fit on the same screen while retaining (IMO) the same functionality. The question we are asking ourselves when working with the matrix is less "what did we estimate story X to be?" but more "what could 5 story points mean; what is an example of 5 story points?", "what's 7?" etc.
Just my two cents of course, there's not just one way of looking at this. Both versions of the matrix would be super useful to us!

**Comment by xeronimus** [comment]
good idea, I quickly changed it to this:  (don't mind all the dummies ;) )

![2022-01-29 15_45_20-Window](https://user-images.githubusercontent.com/1777143/151665399-03e5690a-c257-4f3f-8106-a7014c3c4199.png)

**Comment by xeronimus** [comment]
will the createdAt  date + time bring any value? should I re-add it?

**Comment by mariokaufmann** [comment]
I like it! :) I wonder whether it's even necessary that the stories are all on separate rows. For me personally I wouldn't mind e.g. the 13 story being in the same row of the table as the 1/2 story etc. That could be more space efficient (but of course would then be more of estimation "buckets" than a matrix ;-)  and I don't want to destroy @martin-sos 's idea.

As for the dates: gut feeling is that for me personally they wouldn't add much value to this PoinZ view as we don't really take the age of the issue story into account when estimating. I don't have a strong opinion there though.

**Comment by martin-sos** [comment]
Yeah, I think as well it is more space efficient to have buckets rather than row representation. On the other side, we do not estimate more than 10-15 stories per session...
As the one or the other way may be personal preference, another toggle button might be added? Not sure though whether this adds to much complexity to the tool.

**Comment by xeronimus** [comment]
Thanks for the feedback.  Let's try out the current version... 
I'm happy to hear your feedback - and maybe we get some additional feedback from the community :)
