### ISSUE TITLE
Order the added stories in a way so that newly added stories are easier to find

### ISSUE THREAD

**Issue by michaelschnyder** [Zuehlke/poinz#24]
We tried the solution for our estimation session today and everything worked well.

We added stories on the fly, but with that approach it wasn't easy to find this stories after adding them to the list.

Suggestion 1: Order the stories by the "Create date"? Newest on bottom?
Suggestion 2: Make stories smaller which are not selected
Suggestion 3: Indicate the estimated stories as "Done"

**Comment by xeronimus** [comment]
thanks for the suggestions. I started implementing the following improvements:

- stories are now ordered according to creation timestamp, newest on bottom
- for non-selected stories in story list, text/body is hidden, only title is shown

**Comment by michaelschnyder** [comment]
cool, thank you!
