### ISSUE TITLE
More female heroes as avatars please

### ISSUE THREAD

**Issue by jertyuiop** [Zuehlke/poinz#244]
Hello, this is a new feature request rather than an issue, so please move/remove this if it's in the wrong place.

Please could we have more female heroes as options to be an avatar? Currently the only female avatar is Black Widow and there are 10 male ones.

Suggestions for other female heroes we could include:
The Wasp, Captain Marvel, Ms Marvel (Kamala Khan), Valkyrie, Scarlet Witch, Shuri, Okoye, Gamora, Nebula, Mantis.

Thank you for considering my request.

**Comment by xeronimus** [comment]
what do you think about that?  @jertyuiop 

![image](https://user-images.githubusercontent.com/1777143/153066323-2755aee2-b2b1-47c0-8302-279f03718be4.png)

**Comment by jertyuiop** [comment]
Hi @xeronimus, thanks for getting back so quickly :)

I think that looks great! There's a good range of animals there to suit all sorts of different personalities.

**Comment by xeronimus** [comment]
improvement done and merged to master (we even got two additional animals :) ) 
will be included in next release
