### ISSUE TITLE
Remember Include Trashed Stories Preference

### ISSUE THREAD

**Issue by jertyuiop** [Zuehlke/poinz#250]
Hi team,

We've been using PoinZ for estimation and it's been really good! We've recently started using Story Points and making use of the feature to check previous tickets to use as a benchmark.

When we do that we check the trashed stories as well, the problem is whenever we switch from the "Story" view to the "Estimation Matrix" view we have to tick "include trashed stories" every time.

Is there a way that the page could remember our choice for "include trashed stories", so that if we tick it, change to the Story view, then change back to the Estimation Matrix view, the checkbox is still ticked? And similarly if we untick the box then it stays unticked when we come back to it.

Thanks very much :)

**Comment by xeronimus** [comment]
done, will be in next release

**Comment by jertyuiop** [comment]
Wonderful, thanks very much :)

**Comment by jertyuiop** [comment]
Hi team, thanks again for doing this fix. When is the next release?

**Comment by xeronimus** [comment]
sorry, been quite busy... ;)

released 0.16.0 this morning

**Comment by jertyuiop** [comment]
No worries, brilliant thank you!
