### ISSUE TITLE
Sorting of Items

### ISSUE THREAD

**Issue by hitclif** [Zuehlke/poinz#252]
There are predefined sorts of the items to be estimated (Alphabetical, oldest, newest).
It would be helpful to have a "custom sort" - just drag&drop items in the list.

**Comment by xeronimus** [comment]
Thank you for the suggestion!

Would the custom sorting be room-wide ? (i.e. if one user manually orders the stories, would other users that also selected "manual sort" in the dropdown, also see the same ordering) ?

**Comment by xeronimus** [comment]
![image](https://user-images.githubusercontent.com/1777143/156887218-2486fa1b-8ba2-404f-8fef-e03e02190049.png)

**Comment by hitclif** [comment]
In my opion yes, room-wide.
Additionally anyone in the room may change the order of the stories and this order will then reflect by everyone. My use case is following:
1.) export from jira from a search (using some order most likely RANK order, might be something else)
2.) import to poinz
3.) manually reorder for planning (it's quicker than finding out proper ordering in jira)

Reasons:
- old stories might still be present in PoinZ so the import only adds new ones
- new user stories (eg. split) might be created during planning
- other priority from the team might be requested during the planning/estimation

**Comment by hitclif** [comment]
Expectation:
I don't need to select "Manual Ordering". I just drag&drop a story and the system will automatically switch to "Manual ordering"

**Comment by xeronimus** [comment]
perfect.  

I agree regarding automatically switching to "manual ordering".  However, I still want to have the entry in the dropdown. 
Since the manual ordering is persisted anyways - I might want to quickly switch to "oldest stories first" and then back to my previous manual ordering

**Comment by hitclif** [comment]
That corresponds my expectation.. :)
