### ISSUE TITLE
Applause when the team achieves a consent

### ISSUE THREAD

**Issue by michaelschnyder** [Zuehlke/poinz#26]
I would be nice to have some applause / popup / congrats when the team has achieved a consent on the story points

**Comment by xeronimus** [comment]
story points are now saved and displayed as soon as team achieved consensus (everybody estimated same value)

**Comment by michaelschnyder** [comment]
Awesome! I have to admit that II forgot this feature request entirely, and all of a sudden GitHub shows me a notification indicating a change :) Thanks @xeronimus

**Comment by xeronimus** [comment]
:)  
We now store the estimated value on the story and display it in the backlog.
However, currently no "Hurrah"  popup.  Do you have any preferences?
 
![image](https://user-images.githubusercontent.com/1777143/83492986-68f24d80-a4b4-11ea-94c0-d9bdbb4f0457.png)
