### ISSUE TITLE
Write estimate to jira

### ISSUE THREAD

**Issue by hitclif** [Zuehlke/poinz#266]
I would appreciate if the poinz was able to write the estimate directly to jira.
This functionality could be optional.
When choosing the "winner", poinz would write the number into the Story Points field of the defined story (URL is in the description)

**Comment by xeronimus** [comment]
Hello @hitclif  
that would really be a nice feature. 

However, I don't think that external write access to jira is an easy thing to implement. Somehow you would need to authenticate & authorize PoinZ to be able to write to your jira instance.

**Comment by hitclif** [comment]
Isn't there a way to do it using REST call get or post?
something like https://jira/TicketNumber?StoryPoints=8
