### ISSUE TITLE
Docker hub tags 0.17.x are missing

### ISSUE THREAD

**Issue by egonzalezgmv** [Zuehlke/poinz#284]
Hi,

Since a few releases ago, Docker hub image tags are not being generated, last published tag was 0.16.0:
https://hub.docker.com/r/xeronimus/poinz/tags?page=1&name=0.16.

All 0.17.x are missing:
https://hub.docker.com/r/xeronimus/poinz/tags?page=1&name=0.17.

Master release is well published as latest nevertheless:
https://hub.docker.com/r/xeronimus/poinz/tags?page=1&name=latest

Thank you

**Comment by xeronimus** [comment]
Hi, 

thanks for opening this issue.  Currently I need to manually trigger the github action on the specific git tag (e.g. "0.17.3") on the master branch.
The docker image will be then correctly tagged with the git tag of the respective commit. 


Any ideas how to automatically trigger the github action, if I publish a new release (and also tag the latest master commit) through the github UI?

**Comment by ociotec** [comment]
Thanks a lot!
