### ISSUE TITLE
Allow browser to save password

### ISSUE THREAD

**Issue by hitclif** [Zuehlke/poinz#287]
Everytime I want to open Poinz I need to enter the password. This is a bit annoying. Therefore it would be nice if the password could be managed by the browser and fill in automatically.

**Comment by xeronimus** [comment]
Hi @hitclif ,

I just checked again, the password fields have the following "autocomplete" attribute set:

two password fields in room settings, for setting or changing the password of a room: 

```
<input type="password"  autocomplete="new-password" />
```

One password field when you enter a protected room:

```
<input type="password" autocomplete="current-password" />
```

As defined here (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)  I would expect the browser to correctly autocomplete the field for you..

Or do we have an error here?

**Comment by hitclif** [comment]
I am using the Chrome. I've also tried in Firrefox, doesn't work. The browser didn't even ask to save the password.

**Comment by xeronimus** [comment]
my setup and how I end up with a saved password (maybe it helps us pin-pointing the problem)

1.  Chrome Version 105.0.5195.127 (Official Build) (64-bit) on Windows 10  or   Chrom**ium** Version 90.0.4430.72 (Official Build) on Ubuntu
2.  Make sure, that Chrome can store passwords on the domain **poinz.app*  (Settings > Passwords / Password Manager > "Never Saved" must not contain this domain
3.  go to https://www.poinz.app, create a new random room
4. In the room settings, set a random password
5. Reload the page -> PoinZ wants to join you to the room, presents you with the Password prompt page
6. Enter the password -> Chrome/Chromium displays the "Save password?"  Popup where I leave the username blank.
7. Reload the page. password-field is prefilled
