### ISSUE TITLE
Dedicated URL

### ISSUE THREAD

**Issue by vgt** [Zuehlke/poinz#290]
Are there any plans to move to a dedicated URL with a "unstylized" name? I was able to move a customer team from another tool to poinz, but getting the name and URL across really needs written communication. Just an idea, please close the issue if this is not feasible or wanted.

**Comment by xeronimus** [comment]
Hi there,  sorry for the late reply!

not quite sure if I understand your question.  "unstylized"? 
Are you referring to the URL of the deployed poinz Webapp ?   you can find it here https://www.poinz.app
