### ISSUE TITLE
update dependency "nanoid"  from 3.3.x to 4.x

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#291]
nanoid removed CommonJS support in v 4.x  (see  https://github.com/ai/nanoid/issues/364#issuecomment-1150173952 )

- nanoid is used in poinz */server*  as well as */client*
- just incrementing to 4.0.0 in package.json doesn't do the trick

**Comment by MatteoMolinari93** [comment]
Babel changes the `import`  into `require` and this is not supported in the new version of `nanoid`. Why Babel in the server? The application is delivered in an Image with Node.js, this means that the compatibility is tested and guaranteed, right?

**Comment by xeronimus** [comment]
We can verify what it would need to remove babel from the backend altogether.

We also need a solution for the client. There, babel is certainly needed.

**Comment by MatteoMolinari93** [comment]
#293 
This is roughly what needs to be done on the server side. I had no time to dive into the client, but it does not look good :D

**Comment by xeronimus** [comment]
fixed.

* in the backend we removed babel altogether (thanks @MatteoMolinari93  ). we then could switch to nanoid 4.x      
* in the frontend we're keeping the babel build.  nanoid 4.x is supported by transforming it during unit tests: with jest-babel, transform all node_modules that are not "nanoid" (see transformIgnorePatterns in package.json)  .  thanks @r3dDoX
