### ISSUE TITLE
Manually set Avatar

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#3]
Currently users are assigned one of the avatar icons in sequence (first user gets agent coulson, second user gets black widow, ... ,6th user gets Hulk, etc.)
#### Acceptance Criteria
- Discuss whether users should be able to choose one of the avatars or any avatar (e.g. by url)
- Currently avatar-icons are only known to the client, thus when re-connection (refresh the browser), you get assigned a new icon. We might have to change this, so that the server stores the icon assignment per user.

**Comment by adiherzog** [comment]
In my opinion this is quite low prio / nice to have but some people might be exited by this :-)

**Comment by xeronimus** [comment]
This can be achieved by using Gravatar email address..

**Comment by xeronimus** [comment]
- Let users choose one of the predefined avatars (avengers)
- selection is stored in localStorage (similar to username, userId and email)
- If email address is set, it overrides avatar with matching Gravatar Icon
- By default, no avatar is selected and generic user icon is displayed

**Comment by xeronimus** [comment]
![image](https://user-images.githubusercontent.com/1777143/85233454-99b80980-b406-11ea-8b09-89353dbf1244.png)
