### ISSUE TITLE
Delete stories

### ISSUE THREAD

**Issue by adrianbaertschi** [Zuehlke/poinz#30]
The users should be able to delete sories in the board, similar to the edit feature.

**Acceptance criteria**
- When the user hovers over a story, a delete icon should appear.
- When the user clicks on the delete icon, the story gets removed from the list and deleted in the backend

**Comment by xeronimus** [comment]
I like the idea - thanks!

should we delete stories completely or should we mark them as "deleted", in order to provide a "restore" feature?

**Comment by adrianbaertschi** [comment]
Made a basic implementation which completely deletes the story in redis. Currently it's on this branch: https://github.com/adrianbaertschi/poinz/tree/30-delete-stories.

I think we could change the backend implementation to set a flag "deleted" on the story and filter these out when reading all stories for a room.

**Comment by tknerr** [comment]
How is this supposed to work without ability to delete stories / clean the room? Creating a new room for each sprint?

**Comment by xeronimus** [comment]
various Teams already use Poinz and use it quite differently. Some create a new room for each meeting (e.g. "SuperProject Sprint 35 Planning" ), some reuse the room, some even reuse the same story as a placeholder.

**Comment by tknerr** [comment]
@xeronimus thanks for the info! Didn't think of reusing / renaming stories yet, but yes would be possible. Still, deletion would be nice at some point in time.

Nice tool btw (I forgot to mention that earlier :-))! 👍

**Comment by xeronimus** [comment]
thanks! I'll merge Adrian's PR...

Torben Knerr <notifications@github.com> schrieb am Mo., 20. März 2017,
15:00:

**Comment by xeronimus** [comment]
merged and deployed.

**Comment by tknerr** [comment]
Thanks @xeronimus! 👍
