### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#309]

**Comment by fabioscagliola** [comment]
@xeronimus, please assign this issue to me.

Do we all agree on using the zebra as favicon?

**Comment by xeronimus** [comment]
It's total coincidence, that the Zebra avatar was on index 0, therefore became the default Avatar for all users on first join ;)

I could also imagine a favicon with "three estimation cards fanned out"

**Comment by fabioscagliola** [comment]
@xeronimus, I cannot push my branch including the favicon -- please, help.

By the way, here is what I came up with. Do you like it?

![PoinZ](https://user-images.githubusercontent.com/6649218/209687668-9834aacd-8d99-4dd9-89d3-4fa84815ed04.png)

**Comment by xeronimus** [comment]
wonderful, thanks for the Icon! :)

- Fork the repo
- Push your local branch to your upstream repo (your fork of poinz, will be something like github.chom/fabioscagliola/poinz.git)
- Create a PR from your branch (on your repo) to the master branch on this repo (the /Zuehlke/poinz)

**Comment by fabioscagliola** [comment]
@xeronimus, please see https://github.com/Zuehlke/poinz/pull/315
