### ISSUE TITLE
Preserve "Issue Key" when importing from external tool and exporting again

### ISSUE THREAD

**Issue by xeronimus** [Zuehlke/poinz#323]
### Discussed in https://github.com/Zuehlke/poinz/discussions/320

1. Extend the schema with a new property "key" ("story-key" / "issue-key" ), this should be a optional property (not mandatory)
2. Store this property when importing from csv (still prepend imported issue-key to title)
3. On export (json), include this new property in the export

**Comment by cdwillie76** [comment]
I tested this branch and confirmed that the key was export for csv items that had it during import.

**Comment by cdwillie76** [comment]
Thank you!
