### ISSUE TITLE
The numbers in the cards are too large

### ISSUE THREAD

**Issue by Frickeldave** [Zuehlke/poinz#333]
It is very hard to read the numbers. -> Screenshot

![image](https://user-images.githubusercontent.com/34135598/213223411-aa33adb0-90a6-429f-a8c6-15f1268a4175.png)

**Comment by xeronimus** [comment]
Thanks @Frickeldave  !   could you quickly send me the card config of your room?
("Settings" -> "Custom Cards" -> </ Text>" and den copy paste the json ..)
