### ISSUE TITLE
Create a cup of coffe

### ISSUE THREAD

**Issue by Berthot** [Zuehlke/poinz#334]
Create a cup of coffe card, when a Scrum master or tech writter is in a poker planning he is only watching, and a cup of coffe dont contabilize in pontuation, i think the card "?" is when dont understand how much points to allocate to the task.

![cup of coffe](https://endlessicons.com/wp-content/uploads/2012/09/cup-of-coffee-icon-614x460.png)

**Comment by xeronimus** [comment]
Hi @Berthot 

For colleagues that are only watching, and not estimating themselves (e.g. Scrum Masters), we have the "Spectator" feature.

You can mark a user as "Spectator", then, he will not be able to estimate. Checkout https://github.com/Zuehlke/poinz/blob/master/docu/manual.md#spectator for more information.

Does this already solve your problem?
If not, you can customize the cards in your room yourself. See  https://github.com/Zuehlke/poinz/blob/master/docu/manual.md#custom-cards for more information.

![image](https://user-images.githubusercontent.com/1777143/214123156-014d35f3-434a-4e54-8ca1-37e440cd074c.png)
