### ISSUE TITLE
Add option to show unpointed stories on the estimation matrix view

### ISSUE THREAD

**Issue by cdwillie76** [Zuehlke/poinz#364]
As a team that wants to quickly size stories
We want to ability to show unpointed stories on the estimation matrix view
So that we can quickly view all the stories and size them by dragging/dropping to the correct column

This is a technique some of our "mature" teams do in other tools (digital whiteboard, PowerPoint, etc).  When I demo'ed them Poinz, they asked about doing something similar with the estimate matrix view.

**Comment by xeronimus** [comment]
Hi,

Thanks for the suggestion. That should be possible to implement.
I propose to display all stories without consensus in an additional first column on the left.
By dragging stories from this left-most column to any other column, you would set the estimation value of said story.


Some thoughts:
- Should it be possible to drag stories to this most-left column? This would then clear any estimation value on this story.
- The un-estimated stories don't have a configured color - we need to define how to display those (e.g. white with gray border)

**Comment by cdwillie76** [comment]
Thanks for the quick response and agree with both of the suggestions under some thoughts.

**Comment by xeronimus** [comment]
implemented. included in 0.19.1 release
