### ISSUE TITLE
Import from Jira XML

### ISSUE THREAD

**Issue by aslafy-z** [Zuehlke/poinz#366]
I'd love to import a search result from Jira using their XML export.
This would ease batch estimation of a set of stories.

**Comment by xeronimus** [comment]
Hi @aslafy-z ,

Is the CSV Export / Import a viable alternative for you?   see https://github.com/Zuehlke/poinz/blob/master/docu/manual.md#importing-stories for more information.


if for some reason, your jira instance cannot export csv, would you be able to provide a sample export in XML format?

**Comment by xeronimus** [comment]
Thanks for your input.  there is already a import button implemented (as part of #358). As an additional button in the dropdown (next to filter and ordering).
This will be included in the next release.
