### ISSUE TITLE
Extended visitor rights

### ISSUE THREAD

**Issue by cobba83** [Zuehlke/poinz#46]
Hi,

first of all. Thanks for the app. It's very nice.

We would like to have a Scrum Master Role. 

- This role should be able to add/edit Stories
- This role should not vote for Story Points

It's a mix of visitor and regular user.

**Comment by xeronimus** [comment]
Hi @cobba83 ,  

Thanks very much for the input.

What about renaming the "visitor" flag: We could name it "Exclude from estimations". 
As soon as you set the flag for a user, he can no longer estimate for a story, but still do everything else. 

This would keep it simple, we would not need various "roles" with different rights/privileges.

What do you think?

**Comment by cobba83** [comment]
That sounds really good. I like the idea of keeping it simple.

**Comment by xeronimus** [comment]
I deployed the new version with the "excluded" feature.  please check it out, whether this works for you

**Comment by cobba83** [comment]
Hey, sorry for the late response.
We like the changes you have made.

Thank you a lot.
