### ISSUE TITLE
Feedback Stripe Avatar is Skewed

### ISSUE THREAD

**Issue by jasofalcon** [Zuehlke/poinz#60]
The avatar in bottom left of screen, within "send feedback" box, has its aspect ratio deformed.

<img width="473" alt="Screen Shot 2020-06-11 at 14 13 24" src="https://user-images.githubusercontent.com/22824640/84384327-1caeb800-abee-11ea-9f77-80f3a04c02ed.png">

I would also like to see a cancel (x) button to hide the stripe if someone doesnt want to give feedback.

I can create pull request in next days if that sounds feasible?

**Comment by proticjana** [comment]
Just have in mind it isn't skewed for everyone:

![image](https://user-images.githubusercontent.com/11773304/84386855-5b467180-abf2-11ea-9a93-b69444144504.png)

**Comment by jasofalcon** [comment]
After many refreshes I've managed to get the normal size as well.

However, just found another issue:
Blue feedback box is not fixed when there are many cards, it follows scrolling

<img width="311" alt="Screen Shot 2020-06-11 at 16 01 16" src="https://user-images.githubusercontent.com/22824640/84394204-ec224a80-abfc-11ea-8287-f8717935fb4a.png">

**Comment by jasofalcon** [comment]
After refreshing many times i got the same (normal) view.

However found another issue, when there is many cards and scroll appears, blue feedback box follows scroll instead of staying fixed:

<img width="311" alt="Screen Shot 2020-06-11 at 16 01 16" src="https://user-images.githubusercontent.com/22824640/84394455-415e5c00-abfd-11ea-9a44-8c388f77522e.png">

**Comment by xeronimus** [comment]
Thanks guys.  I will look into it :)

**Comment by jasofalcon** [comment]
I believe left-side menu could be easily created with flex-box styling. Made a pull request which solves the scrolling issue.

**Comment by xeronimus** [comment]
feedback hint can now be hidden by user.
