### ISSUE TITLE
Import from Jira

### ISSUE THREAD

**Issue by sebastianzillessen** [Zuehlke/poinz#76]
Wouldn't it be cool to allow a CSV import from Jira? So that you could simply add all your stories from a csv file that you would like to estimate in this planning?

**Comment by xeronimus** [comment]
I love the idea. Could you provide me with a sample csv export?

**Comment by xeronimus** [comment]
@sebastianzillessen   I implemented issues to story import. currently supports csv with such a structure:  
https://github.com/Zuehlke/poinz/blob/76-import-from-jira/server/test/unit/testJiraIssueExport.csv

does that match your jira export format?

**Comment by xeronimus** [comment]
@sebastianzillessen   I deployed a new version that contains the "import" feature. Would be great if you could check it out.
